# ---------------------- #
# site config            #
# ---------------------- #
name: proxy
baseurl:
url: http://proxy.yeh.sh

# ---------------------- #
# jekyll                 #
# ---------------------- #
safe: true
auto: true
rouge: true
markdown: kramdown
timezone: Asia/Shanghai

# ---------------------- #
# deployment             #
# ---------------------- #
deploy:
repository:
branch:


